SECRET_KEY=728093902sjksdguiehkndnshiue
DEBUG=False
DB_NAME=ahaven
DB_USER=fl0user
DB_PASSWORD=imG4pFu9yONe
DB_HOST=ep-broad-unit-a1whbmdk.ap-southeast-1.aws.neon.fl0.io
DB_PORT=5432
EMAIL_PASSWORD=qazh mteo sqhc hdaq
EMAIL=authorshav3n@gmail.com
SOCIAL_PASSWORD=pgozr2jn7zs_o%i8id6=rddie
TWITTER_CONSUMER_API_KEY=EWBgtt4uIpRldT1ESuruYN1Pu
TWITTER_CONSUMER_API_SECRET=6FpLL1lbjW0IHoWINcPnf0TQyKgebLWbzniUrGUcK7Xuj0TvxV